// DEC-666 (amendment, wave 56): ONE room-absence vocabulary for the whole
// codebase. src/domain/schedule.ts exports ROOM_TBA_LABEL ("To be
// announced") and publicRoomLabel(roomName) as the single place a nullable
// room name becomes public-facing prose. Five other readers used to
// re-declare a private "To be announced"/"Room to be announced" constant or
// inline literal instead of calling publicRoomLabel: those have all been
// deleted in favour of importing from src/domain/schedule.ts directly (in
// src/) or via app/src/lib/room-label.ts (the one named app/ -> src/
// crossing, same idiom as plural.ts's DEC-957/DEC-660). This scan bans any
// OTHER module from declaring a QUOTED string literal containing "to be
// announced" -- prose comments mentioning the phrase are deliberately not
// matched, only genuine string literals a reader could render.
import { readFileSync, readdirSync } from "node:fs";
import { join, relative } from "node:path";
import { describe, expect, it } from "vitest";

const ROOT = join(__dirname, "..");
const SRC_ROOT = join(ROOT, "src");
const APP_SRC_ROOT = join(ROOT, "app", "src");

// The ONE legitimate home for the literal.
const OWNER = "src/domain/schedule.ts";

function isTestFile(path: string): boolean {
  return /\.(test|spec)\.(ts|tsx)$/.test(path);
}

// src/decisions-data/ holds the generated decisions.ts registry -- summary
// prose of every DEC's ruling, regenerated by the scribe, not a UI-rendering
// surface. DEC-666's own text quotes "To be announced" as documentation of
// the ruling it describes, which is not the same violation as a second
// render-path re-declaring the literal.
function isDecisionsDataFile(path: string): boolean {
  return /[\\/]decisions-data[\\/]/.test(path);
}

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...walk(full));
    } else if (
      entry.isFile() &&
      (full.endsWith(".ts") || full.endsWith(".tsx")) &&
      !isTestFile(full) &&
      !isDecisionsDataFile(full)
    ) {
      out.push(full);
    }
  }
  return out;
}

// Only a QUOTED string literal containing the phrase (case-insensitive) --
// not a bare mention in a `//` or `/* */` comment, which is legitimate
// prose describing the behaviour.
const QUOTED_LITERAL = /['"`][^'"`]*to be announced[^'"`]*['"`]/i;

export function findRoomLabelLiteralFiles(root: string, repoRoot: string): string[] {
  const offenders: string[] = [];
  for (const file of walk(root)) {
    const rel = relative(repoRoot, file).split("\\").join("/");
    if (rel === OWNER) continue;
    const contents = readFileSync(file, "utf8");
    if (QUOTED_LITERAL.test(contents)) offenders.push(rel);
  }
  return offenders.sort();
}

describe("room-label-single-source.scan (DEC-666 amendment, wave 56): one room-absence vocabulary", () => {
  it("scanned at least 1 file under src/ and app/src/ (vacuous-scan tripwire)", () => {
    expect(walk(SRC_ROOT).length).toBeGreaterThan(0);
    expect(walk(APP_SRC_ROOT).length).toBeGreaterThan(0);
  });

  it("src/domain/schedule.ts genuinely declares the literal (proves the pattern isn't vacuous)", () => {
    const src = readFileSync(join(ROOT, OWNER), "utf8");
    expect(QUOTED_LITERAL.test(src)).toBe(true);
  });

  it("no module other than src/domain/schedule.ts declares a 'to be announced' string literal", () => {
    const offenders = [...findRoomLabelLiteralFiles(SRC_ROOT, ROOT), ...findRoomLabelLiteralFiles(APP_SRC_ROOT, ROOT)];
    expect(offenders, offenders.join("\n")).toEqual([]);
  });

  it("negative control: a synthetic string literal IS detected", () => {
    const synthetic = "const label = roomName ?? 'To be announced';";
    expect(QUOTED_LITERAL.test(synthetic)).toBe(true);
  });

  it("negative control: a prose comment mentioning the phrase is NOT detected", () => {
    const synthetic = "// an honest To be announced fallback instead of silently omitting the room";
    expect(QUOTED_LITERAL.test(synthetic)).toBe(false);
  });
});
