// Canonical D1 schema per DEC-003 (table names, ID strategy, enum literals),
// DEC-008 (form_field shape), DEC-006 (email_log columns), DEC-010
// (schedule_slot shape), DEC-001 (layout: migrations/ generated by
// drizzle-kit from this file).
//
// IDs are plain text primary keys with no DB-side default: application code
// (src/domain/ids.ts, owned by another wave-1 task) assigns a 20-char
// lowercase base32 id via newId() before insert. Timestamps are integer ms
// epoch (mode: 'timestamp_ms').
//
// This is a barrel: tables live in cohesive submodules alongside this file
// (org.ts, event.ts, submissions.ts, review.ts, scheduling.ts, tasks.ts,
// content.ts, email.ts, crm.ts, org-admin.ts, embed.ts) — split out of a
// single 843-line schema.ts (a merge-conflict hotspot) with no behavior
// change. Every call site imports from "src/db/schema" (this barrel);
// individual submodules are an internal detail.

export * from "./org";
export * from "./event";
export * from "./submissions";
export * from "./review";
export * from "./scheduling";
export * from "./tasks";
export * from "./content";
export * from "./email";
export * from "./crm";
export * from "./org-admin";
export * from "./embed";
