// Canonical D1 schema per DEC-003 (table names, ID strategy, enum literals),
// DEC-008 (form_field shape), DEC-006 (email_log columns), DEC-010
// (schedule_slot shape), DEC-001 (layout: migrations/ generated by
// drizzle-kit from this file).
//
// IDs are plain text primary keys with no DB-side default: application code
// (src/domain/ids.ts, owned by another wave-1 task) assigns a 20-char
// lowercase base32 id via newId() before insert. Timestamps are integer ms
// epoch (mode: 'timestamp_ms').

import { sqliteTable, text, integer, index, uniqueIndex, primaryKey } from "drizzle-orm/sqlite-core";

const id = () => text("id").primaryKey();
const createdAt = () => integer("created_at", { mode: "timestamp_ms" }).notNull();
const updatedAt = () => integer("updated_at", { mode: "timestamp_ms" }).notNull();

// ---------------------------------------------------------------------------
// Org level
// ---------------------------------------------------------------------------

export const org = sqliteTable("org", {
  id: id(),
  name: text("name").notNull(),
  createdAt: createdAt(),
  updatedAt: updatedAt(),
});

export const user = sqliteTable(
  "user",
  {
    id: id(),
    orgId: text("org_id").notNull(),
    email: text("email").notNull(),
    passwordHash: text("password_hash").notNull(),
    // 'organizer' | 'reviewer' | 'speaker' — DEC-004
    role: text("role").notNull(),
    // speaker users link to their person via contact_id — DEC-004
    contactId: text("contact_id"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    user_org_id_idx: index("user_org_id_idx").on(t.orgId),
    user_contact_id_idx: index("user_contact_id_idx").on(t.contactId),
    user_email_idx: uniqueIndex("user_email_idx").on(t.email),
  }),
);

export const authSession = sqliteTable(
  "auth_session",
  {
    id: id(),
    userId: text("user_id").notNull(),
    tokenHash: text("token_hash").notNull(),
    expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    auth_session_user_id_idx: index("auth_session_user_id_idx").on(t.userId),
    auth_session_token_hash_idx: uniqueIndex("auth_session_token_hash_idx").on(t.tokenHash),
  }),
);

export const contact = sqliteTable(
  "contact",
  {
    id: id(),
    orgId: text("org_id").notNull(),
    firstName: text("first_name").notNull(),
    lastName: text("last_name").notNull(),
    email: text("email").notNull(),
    phone: text("phone"),
    company: text("company"),
    title: text("title"),
    bio: text("bio"),
    headshotUrl: text("headshot_url"),
    socialLinksJson: text("social_links_json"),
    notes: text("notes"),
    customFieldsJson: text("custom_fields_json"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    contact_org_id_idx: index("contact_org_id_idx").on(t.orgId),
    contact_email_idx: index("contact_email_idx").on(t.email),
    // DEC-337 (w18): composite covering this wave's contacts list query.
    contact_org_id_last_name_first_name_idx: index("contact_org_id_last_name_first_name_idx").on(
      t.orgId,
      t.lastName,
      t.firstName,
    ),
  }),
);

// ---------------------------------------------------------------------------
// Event level
// ---------------------------------------------------------------------------

export const event = sqliteTable(
  "event",
  {
    id: id(),
    orgId: text("org_id").notNull(),
    name: text("name").notNull(),
    slug: text("slug").notNull(),
    startDate: text("start_date").notNull(),
    endDate: text("end_date").notNull(),
    location: text("location"),
    // IANA timezone string
    timezone: text("timezone").notNull(),
    // display ref = `${recordPrefix}-${seq}` e.g. SES-014 — DEC-003
    recordPrefix: text("record_prefix").notNull().default("SES"),
    brandingJson: text("branding_json"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    event_org_id_idx: index("event_org_id_idx").on(t.orgId),
    event_slug_idx: uniqueIndex("event_slug_idx").on(t.slug),
  }),
);

export const form = sqliteTable(
  "form",
  {
    id: id(),
    eventId: text("event_id").notNull(),
    title: text("title").notNull(),
    description: text("description"),
    isDefault: integer("is_default", { mode: "boolean" }).notNull().default(false),
    // w2-c: CFP form open/close window; description doubles as intro text.
    openDate: integer("open_date", { mode: "timestamp_ms" }),
    closeDate: integer("close_date", { mode: "timestamp_ms" }),
    // DEC-015: JSON array of track ids offered on this form; null/empty
    // means all event tracks are offered.
    tracksJson: text("tracks_json"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    form_event_id_idx: index("form_event_id_idx").on(t.eventId),
  }),
);

export const formField = sqliteTable(
  "form_field",
  {
    id: id(),
    formId: text("form_id").notNull(),
    // 'session' | 'speaker' — DEC-008
    section: text("section").notNull(),
    // 'text' | 'long_text' | 'dropdown' | 'checkbox' | 'number' | 'file' — DEC-008
    kind: text("kind").notNull(),
    label: text("label").notNull(),
    helpText: text("help_text"),
    required: integer("required", { mode: "boolean" }).notNull().default(false),
    position: integer("position").notNull().default(0),
    // string[] for 'dropdown'
    optionsJson: text("options_json"),
    // { fieldId, op: 'eq'|'ne'|'in', value } for conditional visibility
    ruleJson: text("rule_json"),
    // locked built-ins (session Title/Description, speaker first/last/email)
    // are required + non-removable
    locked: integer("locked", { mode: "boolean" }).notNull().default(false),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    form_field_form_id_idx: index("form_field_form_id_idx").on(t.formId),
    form_field_form_id_position_idx: index("form_field_form_id_position_idx").on(t.formId, t.position),
  }),
);

export const submission = sqliteTable(
  "submission",
  {
    id: id(),
    eventId: text("event_id").notNull(),
    formId: text("form_id"),
    // integer, unique per event — display ref uses event.record_prefix
    seq: integer("seq").notNull(),
    title: text("title").notNull(),
    description: text("description"),
    trackId: text("track_id"),
    // secondary tracks beyond the primary track_id, string[] of track ids
    additionalTrackIdsJson: text("additional_track_ids_json"),
    // 'pending' | 'accept_queue' | 'decline_queue' | 'accepted' | 'declined' (+ custom) — DEC-003
    status: text("status").notNull().default("pending"),
    // 'pending' | 'approved' | 'changes_requested' — DEC-003
    contentStatus: text("content_status").notNull().default("pending"),
    // nullable; guards idempotent acceptance side effects — DEC-009
    acceptedAt: integer("accepted_at", { mode: "timestamp_ms" }),
    // bumped by the caller on schedule-affecting changes — DEC-007
    icsSequence: integer("ics_sequence").notNull().default(0),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    submission_event_id_idx: index("submission_event_id_idx").on(t.eventId),
    submission_form_id_idx: index("submission_form_id_idx").on(t.formId),
    submission_track_id_idx: index("submission_track_id_idx").on(t.trackId),
    submission_event_id_status_idx: index("submission_event_id_status_idx").on(t.eventId, t.status),
    submission_event_id_seq_idx: uniqueIndex("submission_event_id_seq_idx").on(t.eventId, t.seq),
    // DEC-337 (w18): composite covering this wave's paginated submissions list.
    submission_event_id_created_at_idx: index("submission_event_id_created_at_idx").on(t.eventId, t.createdAt),
  }),
);

export const submissionAnswer = sqliteTable(
  "submission_answer",
  {
    id: id(),
    submissionId: text("submission_id").notNull(),
    formFieldId: text("form_field_id").notNull(),
    valueJson: text("value_json").notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    submission_answer_submission_id_idx: index("submission_answer_submission_id_idx").on(t.submissionId),
    submission_answer_form_field_id_idx: index("submission_answer_form_field_id_idx").on(t.formFieldId),
    submission_answer_submission_id_form_field_id_idx: uniqueIndex("submission_answer_submission_id_form_field_id_idx").on(
      t.submissionId,
      t.formFieldId,
    ),
  }),
);

// DEC-015: talks are submitted to one or more tracks; track membership is a
// real join (never a form_field answer) so reviewer assignment, filtering,
// and the agenda can all key on it.
export const submissionTrack = sqliteTable(
  "submission_track",
  {
    submissionId: text("submission_id").notNull(),
    trackId: text("track_id").notNull(),
    createdAt: createdAt(),
  },
  (t) => ({
    submission_track_pk: primaryKey({ columns: [t.submissionId, t.trackId] }),
    submission_track_submission_id_idx: index("submission_track_submission_id_idx").on(t.submissionId),
    submission_track_track_id_idx: index("submission_track_track_id_idx").on(t.trackId),
  }),
);

export const participant = sqliteTable(
  "participant",
  {
    id: id(),
    submissionId: text("submission_id").notNull(),
    contactId: text("contact_id").notNull(),
    role: text("role").notNull().default("speaker"),
    order: integer("order").notNull().default(0),
    visible: integer("visible", { mode: "boolean" }).notNull().default(true),
    // 'none' | 'invited' | 'accepted' | 'declined' — DEC-003
    inviteStatus: text("invite_status").notNull().default("none"),
    // DEC-258: frozen attribution snapshot of contact.title/company as of
    // participant creation. Nullable; public/export/ics reads use this
    // snapshot ONLY (no fallback to live contact). CRM/portal continue to
    // read the live contact fields — that split is deliberate.
    titleAtTime: text("title_at_time"),
    orgAtTime: text("org_at_time"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    participant_submission_id_idx: index("participant_submission_id_idx").on(t.submissionId),
    participant_contact_id_idx: index("participant_contact_id_idx").on(t.contactId),
  }),
);

export const evaluationPlan = sqliteTable(
  "evaluation_plan",
  {
    id: id(),
    eventId: text("event_id").notNull(),
    name: text("name").notNull(),
    instructions: text("instructions"),
    openDate: integer("open_date", { mode: "timestamp_ms" }),
    closeDate: integer("close_date", { mode: "timestamp_ms" }),
    // session filters, e.g. track ids
    filtersJson: text("filters_json"),
    anonymized: integer("anonymized", { mode: "boolean" }).notNull().default(false),
    // rating scale definition, e.g. { min, max, labels }
    scaleJson: text("scale_json").notNull(),
    // weighted criteria, e.g. [{ id, label, weight }]
    criteriaJson: text("criteria_json").notNull(),
    rounds: integer("rounds").notNull().default(1),
    // DEC-082: the round an organizer has advanced this plan to (1-based,
    // capped at `rounds` by advancePlanRound). migrations/0009_review_rounds.sql.
    currentRound: integer("current_round").notNull().default(1),
    // DEC-147: nullable map of round -> criteria array override, e.g.
    // {"2":[{id,label,kind,...}]}. Rounds absent from this map (including
    // round 1 by convention) fall back to criteriaJson -- resolved ONLY via
    // src/domain/evaluation.ts's criteriaForRound(). migrations/0010_round_criteria.sql.
    roundCriteriaJson: text("round_criteria_json"),
    maxEvaluations: integer("max_evaluations"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    evaluation_plan_event_id_idx: index("evaluation_plan_event_id_idx").on(t.eventId),
  }),
);

export const planReviewer = sqliteTable(
  "plan_reviewer",
  {
    id: id(),
    planId: text("plan_id").notNull(),
    userId: text("user_id").notNull(),
    // assignment scope: a track (reviewers review one or more tracks), null = all
    trackId: text("track_id"),
    // migrations/0004 (DEC-017): a single-submission assignment scope. Scope
    // semantics: trackId set = all plan submissions in that track;
    // submissionId set = that single submission; both null = all submissions
    // matching plan filters; a reviewer's assignment is the union of their rows.
    submissionId: text("submission_id"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    plan_reviewer_plan_id_idx: index("plan_reviewer_plan_id_idx").on(t.planId),
    plan_reviewer_user_id_idx: index("plan_reviewer_user_id_idx").on(t.userId),
    plan_reviewer_submission_id_idx: index("plan_reviewer_submission_id_idx").on(t.submissionId),
    plan_reviewer_track_id_idx: index("plan_reviewer_track_id_idx").on(t.trackId),
  }),
);

export const evaluation = sqliteTable(
  "evaluation",
  {
    id: id(),
    planId: text("plan_id").notNull(),
    submissionId: text("submission_id").notNull(),
    reviewerId: text("reviewer_id").notNull(),
    round: integer("round").notNull().default(1),
    // per-criterion numeric/dropdown scores, e.g. { criterionId: value }
    scoresJson: text("scores_json").notNull(),
    comment: text("comment"),
    submittedAt: integer("submitted_at", { mode: "timestamp_ms" }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    evaluation_plan_id_idx: index("evaluation_plan_id_idx").on(t.planId),
    evaluation_submission_id_idx: index("evaluation_submission_id_idx").on(t.submissionId),
    evaluation_reviewer_id_idx: index("evaluation_reviewer_id_idx").on(t.reviewerId),
    evaluation_plan_submission_reviewer_round_idx: uniqueIndex("evaluation_plan_submission_reviewer_round_idx").on(
      t.planId,
      t.submissionId,
      t.reviewerId,
      t.round,
    ),
  }),
);

// DEC-271 (task w5-c): reviewer conflict-of-interest / recusal. A reviewer
// may recuse themselves from a submission within a plan; recused submissions
// are excluded from that reviewer's queue and scoring is blocked (409).
export const reviewRecusal = sqliteTable(
  "review_recusal",
  {
    id: id(),
    planId: text("plan_id").notNull(),
    submissionId: text("submission_id").notNull(),
    userId: text("user_id").notNull(),
    reason: text("reason"),
    createdAt: createdAt(),
  },
  (t) => ({
    review_recusal_plan_id_idx: index("review_recusal_plan_id_idx").on(t.planId),
    review_recusal_submission_id_idx: index("review_recusal_submission_id_idx").on(t.submissionId),
    review_recusal_user_id_idx: index("review_recusal_user_id_idx").on(t.userId),
    review_recusal_plan_submission_user_idx: uniqueIndex("review_recusal_plan_submission_user_idx").on(
      t.planId,
      t.submissionId,
      t.userId,
    ),
  }),
);

export const track = sqliteTable(
  "track",
  {
    id: id(),
    eventId: text("event_id").notNull(),
    name: text("name").notNull(),
    color: text("color"),
    position: integer("position").notNull().default(0),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    track_event_id_idx: index("track_event_id_idx").on(t.eventId),
  }),
);

export const room = sqliteTable(
  "room",
  {
    id: id(),
    eventId: text("event_id").notNull(),
    name: text("name").notNull(),
    capacity: integer("capacity"),
    position: integer("position").notNull().default(0),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    room_event_id_idx: index("room_event_id_idx").on(t.eventId),
  }),
);

export const scheduleSlot = sqliteTable(
  "schedule_slot",
  {
    id: id(),
    submissionId: text("submission_id").notNull(),
    // nullable room: "TBD is a real value" — DEC-010
    roomId: text("room_id"),
    // 'YYYY-MM-DD' in event timezone
    day: text("day").notNull(),
    // minutes-from-midnight in event timezone
    startMin: integer("start_min").notNull(),
    endMin: integer("end_min").notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    schedule_slot_submission_id_idx: uniqueIndex("schedule_slot_submission_id_idx").on(t.submissionId),
    schedule_slot_room_id_idx: index("schedule_slot_room_id_idx").on(t.roomId),
    schedule_slot_day_idx: index("schedule_slot_day_idx").on(t.day),
  }),
);

export const task = sqliteTable(
  "task",
  {
    id: id(),
    eventId: text("event_id").notNull(),
    // 'general' | 'file_request' | 'form' — DEC-003
    kind: text("kind").notNull(),
    title: text("title").notNull(),
    description: text("description"),
    dueDate: integer("due_date", { mode: "timestamp_ms" }),
    required: integer("required", { mode: "boolean" }).notNull().default(false),
    // for kind='form' tasks, the form to fill out
    formId: text("form_id"),
    // migrations/0014 (DEC-240): 'presentation' | 'poster' | 'handout',
    // meaningful only when kind='file_request' — the content-pipeline file
    // kind portal uploads for this task should use (defaults to 'handout'
    // at the upload site when unset).
    deliverableKind: text("deliverable_kind"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    task_event_id_idx: index("task_event_id_idx").on(t.eventId),
    task_form_id_idx: index("task_form_id_idx").on(t.formId),
  }),
);

export const taskAssignment = sqliteTable(
  "task_assignment",
  {
    id: id(),
    taskId: text("task_id").notNull(),
    contactId: text("contact_id").notNull(),
    status: text("status").notNull().default("pending"),
    completedAt: integer("completed_at", { mode: "timestamp_ms" }),
    completedBy: text("completed_by"),
    // migrations/0004 (DEC-017): kind='form' task answers, JSON map
    // fieldId->value.
    responseJson: text("response_json"),
    // migrations/0004 (DEC-017): kind='file_request' completion link.
    fileId: text("file_id"),
    // migrations/0004 (DEC-017): reminder dedupe, ms epoch (DEC-023).

    lastRemindedAt: integer("last_reminded_at", { mode: "timestamp_ms" }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    task_assignment_task_id_idx: index("task_assignment_task_id_idx").on(t.taskId),
    task_assignment_contact_id_idx: index("task_assignment_contact_id_idx").on(t.contactId),
    task_assignment_file_id_idx: index("task_assignment_file_id_idx").on(t.fileId),
  }),
);

export const portalSettings = sqliteTable(
  "portal_settings",
  {
    id: id(),
    eventId: text("event_id").notNull(),
    logoUrl: text("logo_url"),
    accentColor: text("accent_color"),
    welcomeMessage: text("welcome_message"),
    showResources: integer("show_resources", { mode: "boolean" }).notNull().default(true),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    portal_settings_event_id_idx: uniqueIndex("portal_settings_event_id_idx").on(t.eventId),
  }),
);

export const resource = sqliteTable(
  "resource",
  {
    id: id(),
    eventId: text("event_id").notNull(),
    // 'file' | 'wiki'
    kind: text("kind").notNull(),
    title: text("title").notNull(),
    // wiki page body (markdown/html) when kind='wiki'
    content: text("content"),
    // uploaded file when kind='file'
    fileId: text("file_id"),
    position: integer("position").notNull().default(0),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    resource_event_id_idx: index("resource_event_id_idx").on(t.eventId),
    resource_file_id_idx: index("resource_file_id_idx").on(t.fileId),
  }),
);

export const file = sqliteTable(
  "file",
  {
    id: id(),
    // nullable: resource files (headshots, standalone resources) aren't
    // attached to a submission
    submissionId: text("submission_id"),
    // 'presentation' | 'poster' | 'handout' — DEC-003
    kind: text("kind").notNull(),
    filename: text("filename").notNull(),
    r2Key: text("r2_key").notNull(),
    sizeBytes: integer("size_bytes").notNull(),
    contentType: text("content_type").notNull(),
    // version chain — DEC-003
    previousFileId: text("previous_file_id"),
    uploadedByContactId: text("uploaded_by_contact_id"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    file_submission_id_idx: index("file_submission_id_idx").on(t.submissionId),
    file_previous_file_id_idx: index("file_previous_file_id_idx").on(t.previousFileId),
    file_uploaded_by_contact_id_idx: index("file_uploaded_by_contact_id_idx").on(t.uploadedByContactId),
  }),
);

export const fileComment = sqliteTable(
  "file_comment",
  {
    id: id(),
    fileId: text("file_id").notNull(),
    authorContactId: text("author_contact_id"),
    authorUserId: text("author_user_id"),
    body: text("body").notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    file_comment_file_id_idx: index("file_comment_file_id_idx").on(t.fileId),
    file_comment_author_contact_id_idx: index("file_comment_author_contact_id_idx").on(t.authorContactId),
    file_comment_author_user_id_idx: index("file_comment_author_user_id_idx").on(t.authorUserId),
  }),
);

export const emailTemplate = sqliteTable(
  "email_template",
  {
    id: id(),
    eventId: text("event_id").notNull(),
    name: text("name").notNull(),
    subject: text("subject").notNull(),
    bodyText: text("body_text").notNull(),
    bodyHtml: text("body_html"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    email_template_event_id_idx: index("email_template_event_id_idx").on(t.eventId),
  }),
);

// migrations/0005_w4_segment.sql (DEC-025, task w4-c): CRM saved-segment
// rules (DEC-026), rules_json holds SegmentRule[] from src/domain/contacts.ts.
export const segment = sqliteTable(
  "segment",
  {
    id: id(),
    orgId: text("org_id").notNull(),
    name: text("name").notNull(),
    rulesJson: text("rules_json").notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    segment_org_id_idx: index("segment_org_id_idx").on(t.orgId),
  }),
);

// migrations/0006_w4_api_token.sql (DEC-025, task w4-e): bearer API tokens
// (DEC-027). Plaintext ('chq_' + 40 lowercase base32 chars) is shown exactly
// once at creation; only its sha256 hex digest is persisted, plus the first
// 12 plaintext chars for display purposes.
export const apiToken = sqliteTable(
  "api_token",
  {
    id: id(),
    orgId: text("org_id").notNull(),
    name: text("name").notNull(),
    tokenHash: text("token_hash").notNull(),
    tokenPrefix: text("token_prefix").notNull(),
    createdByUserId: text("created_by_user_id").notNull(),
    lastUsedAt: integer("last_used_at", { mode: "timestamp_ms" }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    api_token_token_hash_idx: uniqueIndex("api_token_token_hash_idx").on(t.tokenHash),
    api_token_org_id_idx: index("api_token_org_id_idx").on(t.orgId),
    api_token_created_by_user_id_idx: index("api_token_created_by_user_id_idx").on(t.createdByUserId),
  }),
);

// migrations/0007_w4_saved_view.sql (DEC-025, task w4-g): organizer-shared
// Submissions saved views. config_json shape per DEC-031: { q, status[],
// trackId, sort, columns[] } matching the landed submissions filter/column
// state shapes exactly.
export const savedView = sqliteTable(
  "saved_view",
  {
    id: id(),
    eventId: text("event_id").notNull(),
    name: text("name").notNull(),
    configJson: text("config_json").notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    saved_view_event_id_idx: index("saved_view_event_id_idx").on(t.eventId),
  }),
);

// migrations/0012_pipeline.sql (DEC-157, task w3-a): CRM sourcing pipeline
// (CRM-07/08). pipeline_entry is one row per contact enrolled into an org's
// pipeline (fixed stage enum 'identified' | 'contacted' | 'interested' |
// 'confirmed' | 'declined', unique per org+contact); pipeline_activity is an
// append-only 'move'|'note' feed that doubles as both stage history and the
// notes composer's backing store.
export const pipelineEntry = sqliteTable(
  "pipeline_entry",
  {
    id: id(),
    orgId: text("org_id").notNull(),
    contactId: text("contact_id").notNull(),
    stage: text("stage").notNull().default("identified"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    pipeline_entry_org_id_contact_id_idx: uniqueIndex("pipeline_entry_org_id_contact_id_idx").on(t.orgId, t.contactId),
    pipeline_entry_org_id_idx: index("pipeline_entry_org_id_idx").on(t.orgId),
    pipeline_entry_contact_id_idx: index("pipeline_entry_contact_id_idx").on(t.contactId),
  }),
);

export const pipelineActivity = sqliteTable(
  "pipeline_activity",
  {
    id: id(),
    entryId: text("entry_id").notNull(),
    // 'move' | 'note'
    kind: text("kind").notNull(),
    body: text("body"),
    fromStage: text("from_stage"),
    toStage: text("to_stage"),
    authorUserId: text("author_user_id").notNull(),
    authorName: text("author_name").notNull(),
    createdAt: createdAt(),
  },
  (t) => ({
    pipeline_activity_entry_id_idx: index("pipeline_activity_entry_id_idx").on(t.entryId),
    pipeline_activity_author_user_id_idx: index("pipeline_activity_author_user_id_idx").on(t.authorUserId),
  }),
);

// migrations/0013_submission_revision.sql (DEC-158, task w3-b): CNT-11
// session content history. Appended by exactly two write paths (organizer
// PATCH /submissions/:id and portal-edit's locked-field sync), only when
// title/description actually changed; restore re-applies a snapshot
// through the same paths so it lands its own row too. editor_user_id is
// nullable because the portal-edit path is authenticated as a speaker
// contact, not a `user` row — editor_name is always a snapshot string so
// history reads correctly even if the editor is later renamed/deleted.
export const submissionRevision = sqliteTable(
  "submission_revision",
  {
    id: id(),
    submissionId: text("submission_id").notNull(),
    editorUserId: text("editor_user_id"),
    editorName: text("editor_name").notNull(),
    title: text("title").notNull(),
    description: text("description"),
    createdAt: createdAt(),
  },
  (t) => ({
    submission_revision_submission_id_idx: index("submission_revision_submission_id_idx").on(t.submissionId),
    submission_revision_editor_user_id_idx: index("submission_revision_editor_user_id_idx").on(t.editorUserId),
  }),
);

export const emailLog = sqliteTable(
  "email_log",
  {
    id: id(),
    eventId: text("event_id").notNull(),
    templateId: text("template_id"),
    contactId: text("contact_id"),
    toEmail: text("to_email").notNull(),
    // rendered content inline — DEC-006
    subject: text("subject").notNull(),
    bodyText: text("body_text").notNull(),
    bodyHtml: text("body_html"),
    icsText: text("ics_text"),
    // migrations/0002: DEC-006 omitted this column, but the /dev/mailbox
    // download link needs the original filename (w2-i, additive per DEC-015).
    icsFilename: text("ics_filename"),
    provider: text("provider").notNull().default("dev"),
    status: text("status").notNull().default("sent"),
    sentAt: integer("sent_at", { mode: "timestamp_ms" }).notNull(),
    createdAt: createdAt(),
  },
  (t) => ({
    email_log_event_id_idx: index("email_log_event_id_idx").on(t.eventId),
    email_log_template_id_idx: index("email_log_template_id_idx").on(t.templateId),
    email_log_contact_id_idx: index("email_log_contact_id_idx").on(t.contactId),
    // DEC-337 (w18): composite covering this wave's event email log queries.
    email_log_event_id_sent_at_idx: index("email_log_event_id_sent_at_idx").on(t.eventId, t.sentAt),
  }),
);
