// Reassembles docs/verification-log.md from the per-entry files under
// docs/verification-log/index/. This is a pure concatenation (no
// reformatting) so the assembled file is byte-identical to hand-editing the
// monolith directly, except that appends now touch a NEW file under
// docs/verification-log/index/ instead of the shared docs/verification-log.md
// tail -- see docs/verification-log/index/README.md for why (contention
// decomposition, no DEC yet).
//
// Usage (npm entry points: verification-log:assemble / :check / :renumber):
//   tsx scripts/assemble-verification-log.ts             # rewrite docs/verification-log.md
//   tsx scripts/assemble-verification-log.ts --check      # exit 1 if out of date (CI use)
//   tsx scripts/assemble-verification-log.ts --next-seq   # print next 4-digit sequence prefix
//   tsx scripts/assemble-verification-log.ts --renumber   # DEC-068 wave-39: mechanically
//                                                          # resolve colliding 4-digit prefixes
//                                                          # by renaming files on disk, then
//                                                          # re-assemble.

import { readdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dirname, "..");
const INDEX_DIR = join(ROOT, "docs", "verification-log", "index");
const OUTPUT_FILE = join(ROOT, "docs", "verification-log.md");

const PREAMBLE = `# Verification Log
Append-only. One dated section per run.

Per-run full detail lives under \`docs/verification-log/<file>.md\` (one file
per section below, extracted to reduce merge contention on this file — see
DEC-068/DEC-069). Each section here keeps the exact \`## <date> <branch> —
<scope> @ <sha>\` header and, where applicable, the closing \`RESULT:\` /
\`OPEN ITEMS:\` line verbatim, so this file alone remains sufficient for the
DEC-069 exit-predicate grep.

This file is generated by \`tsx scripts/assemble-verification-log.ts\` from
the per-run entry files under \`docs/verification-log/index/\` (sequence-
numbered, one file per section, in append order). Do not hand-edit the
sections below -- add a new file under \`docs/verification-log/index/\` and
re-run the assembler. This split exists purely to stop concurrent branches
from all editing the same file tail; the assembled output is unchanged.
`;

function entryFiles(): string[] {
  return readdirSync(INDEX_DIR)
    .filter((f) => /^\d{4}-.*\.md$/.test(f))
    .sort();
}

// DEC-068 header contract, deliberately mirrored (not imported --
// exit-predicate.ts does not export it, and the wave-45/46 overlap notes say
// never edit exit-predicate.ts beyond importing from it) from
// scripts/exit-predicate.ts:36's HEADER_RE. A section's first line must read
// `## <date> <branch> — <scope> @ <sha>` (EM DASH U+2014) with nothing
// trailing the sha. exit-predicate.ts's parseLogSections only starts a new
// LogSection on a line matching this regex -- any index file whose first
// line does not match is invisible as its own section AND silently donates
// its body's RESULT:/OPEN ITEMS: lines to whichever PRECEDING conforming
// section's body it falls into, overwriting that section's verdict
// (task-w45-f finding).
//
// Two consumers, landed by two different wave lanes and deduplicated here by
// the wave-46 merge train (both lanes had declared this constant separately
// and byte-identically, which git auto-merged into a duplicate-symbol
// TransformError): reportNonConformingHeaders (task-w45-f, report-only) and
// assembleEntry (task-w46-b) -- the latter uses it to detect whether an
// index file's first line already conforms, in which case the file is
// emitted byte-unchanged; DEC-068 wave-46 amendment.
const HEADER_RE = /^## (\d{4}-\d{2}-\d{2}) (\S+) — (.+) @ (\S+)\s*$/;

// DEC-068 wave-46: index filenames encode
// `NNNN-YYYY-MM-DD-<branch>-<scope-words>-<sha>.md` positionally -- the
// trailing hyphen-segment before `.md` IS the sha field (whatever string it
// is; HEADER_RE's own `@ (\S+)` does not require it to look like a hex git
// sha, and several real headers already in this log are not one either), and
// the branch is the `task-w<N>-<letter>` token immediately after the date.
// This is intentionally NOT hex-validated: an earlier draft of this fix
// required the trailing token to look like a hex sha and found 14 files
// under docs/verification-log/index/ (wave 12-21 vintage, e.g. `0143`,
// `0146`) whose filenames were either truncated at 80 chars or never carried
// a sha at all -- hex-validating would throw on all of them and break
// `npm run verification-log:assemble` outright. The header contract itself
// (`HEADER_RE` above) never validates the sha's shape either, so taking the
// filename's trailing segment verbatim is not a relaxation of the contract,
// just a refusal to invent a stricter one than the contract already has.
const FILENAME_RE = /^\d{4}-(\d{4}-\d{2}-\d{2})-(task-w\d+-[a-z]+)-(.+)\.md$/;

/**
 * Derives a synthetic, HEADER_RE-conforming header line from an index
 * filename, per DEC-068's wave-46 amendment: `## <date> <branch> —
 * <scope words> @ <sha>`, with `<sha>` being the filename's trailing
 * hyphen-segment and `<scope words>` every segment between the branch and
 * the sha, hyphens replaced with spaces. Throws loudly if the filename does
 * not even match the base `NNNN-YYYY-MM-DD-task-w<N>-<letter>-...md` shape,
 * or if there is no segment left over to serve as sha/scope after the
 * branch (i.e. nothing between the branch and `.md`).
 */
export function deriveSyntheticHeader(filename: string): string {
  const m = FILENAME_RE.exec(filename);
  if (!m) {
    throw new Error(
      `assemble-verification-log: cannot synthesize a header for ${filename} -- filename does not match the NNNN-YYYY-MM-DD-<branch>-<scope-words>-<sha>.md contract (DEC-068 wave-46 amendment).`,
    );
  }
  const date = m[1] as string;
  const branch = m[2] as string;
  const tail = m[3] as string;
  const tokens = tail.split("-").filter((t) => t.length > 0);
  if (tokens.length < 1) {
    throw new Error(
      `assemble-verification-log: cannot synthesize a header for ${filename} -- nothing between branch "${branch}" and ".md" to serve as scope-words/sha (DEC-068 wave-46 amendment).`,
    );
  }
  const sha = tokens[tokens.length - 1] as string;
  const scopeWords = tokens.slice(0, -1).join(" ");
  if (scopeWords.length === 0) {
    throw new Error(
      `assemble-verification-log: cannot synthesize a header for ${filename} -- only a trailing sha-like segment "${sha}" and no scope words (DEC-068 wave-46 amendment).`,
    );
  }
  return `## ${date} ${branch} — ${scopeWords} @ ${sha}`;
}

/**
 * Emits one entry file's assembled contents. If the file's first line
 * already conforms to HEADER_RE, the file is returned byte-unchanged (the
 * conforming path stays byte-identical, DEC-068 wave-46 amendment
 * acceptance). Otherwise a synthetic header (see `deriveSyntheticHeader`) is
 * prepended and the file's ORIGINAL first line is kept as the section's
 * first body line, so nothing published is lost -- never by editing the
 * index file itself.
 */
export function assembleEntry(filename: string, content: string): string {
  const firstLine = content.split("\n")[0] ?? "";
  if (HEADER_RE.test(firstLine)) {
    return content;
  }
  const synthetic = deriveSyntheticHeader(filename);
  return `${synthetic}\n${content}`;
}

// DEC-068 wave-37 amendment: nextSeq() mints one past the HIGHEST existing
// prefix, so every concurrent lane in a wave gets the same number by
// construction -- wave 35's merge train hand-renumbered a silent 0188
// collision and no test caught it. Detection belongs in the instrument:
// both --check and the default write path call this and fail loudly on any
// duplicate 4-digit prefix, naming every colliding file.
export function duplicateSequences(files: readonly string[]): string[] {
  const byPrefix = new Map<string, string[]>();
  for (const f of files) {
    const prefix = f.slice(0, 4);
    const existing = byPrefix.get(prefix);
    if (existing) {
      existing.push(f);
    } else {
      byPrefix.set(prefix, [f]);
    }
  }
  const collisions: string[] = [];
  for (const group of byPrefix.values()) {
    if (group.length > 1) {
      collisions.push(...group);
    }
  }
  return collisions.sort();
}

function assertNoDuplicateSequences(files: readonly string[]): void {
  const collisions = duplicateSequences(files);
  if (collisions.length > 0) {
    throw new Error(
      `assemble-verification-log: duplicate 4-digit sequence prefix among: ${collisions.join(
        ", ",
      )} -- nextSeq() mints one past the highest prefix, so concurrent lanes in one wave collide by construction (DEC-068 wave-37 amendment). Remediation: renumber every file but the earliest-dated one in each colliding group to the next free sequence(s), then re-run \`tsx scripts/assemble-verification-log.ts\`.`,
    );
  }
}

// DEC-068 wave-39: pure planner for the collision remedy. nextSeq() mints one
// past the highest existing prefix, so every concurrent lane in a wave gets
// the same number by construction (see assertNoDuplicateSequences above) --
// wave 39's own tip commit was a merge-train HAND-renumber of a 0191
// collision. This function replaces the hand-edit with a deterministic,
// unit-tested plan: within each colliding 4-digit group, the file whose
// (date, branch, ...) substring -- i.e. everything after the "NNNN-" prefix,
// which starts with the date then the branch name -- sorts first KEEPS the
// existing sequence; every other file in the group is reassigned, in that
// same sorted order, to the next FREE sequence (never a sequence already in
// use by any file, colliding or not, and never one just claimed by this same
// renumber pass). Non-colliding files are never touched, file content is
// never touched, and files sharing a sequence with no other file are left
// alone. Returns an empty plan when there are no collisions.
export function planRenumber(files: readonly string[]): Array<{ from: string; to: string }> {
  const groups = new Map<string, string[]>();
  for (const f of files) {
    const prefix = f.slice(0, 4);
    const existing = groups.get(prefix);
    if (existing) {
      existing.push(f);
    } else {
      groups.set(prefix, [f]);
    }
  }

  const usedPrefixes = new Set(groups.keys());
  let maxNum = 0;
  for (const prefix of usedPrefixes) {
    const n = Number.parseInt(prefix, 10);
    if (n > maxNum) maxNum = n;
  }
  let candidate = maxNum + 1;
  const claimNextFreeSeq = (): string => {
    let seq = String(candidate).padStart(4, "0");
    while (usedPrefixes.has(seq)) {
      candidate += 1;
      seq = String(candidate).padStart(4, "0");
    }
    usedPrefixes.add(seq);
    candidate += 1;
    return seq;
  };

  const collidingPrefixes = [...groups.entries()]
    .filter(([, group]) => group.length > 1)
    .map(([prefix]) => prefix)
    .sort();

  const plan: Array<{ from: string; to: string }> = [];
  for (const prefix of collidingPrefixes) {
    const group = groups.get(prefix);
    if (!group) continue;
    const sorted = [...group].sort((a, b) => a.slice(5).localeCompare(b.slice(5)));
    // sorted[0] keeps the existing sequence; the rest are renumbered in
    // sorted order.
    for (const f of sorted.slice(1)) {
      const seq = claimNextFreeSeq();
      plan.push({ from: f, to: seq + f.slice(4) });
    }
  }
  return plan;
}

// HEADER_RE is declared once at the top of this module (see its comment
// there); both this reporter and assembleEntry consume that single copy.
export function nonConformingHeaders(
  entries: ReadonlyArray<{ file: string; firstLine: string }>,
): string[] {
  return entries.filter((e) => !HEADER_RE.test(e.firstLine)).map((e) => e.file);
}

// task-w45-f (DEC-068 wave-45 ruling (a)) originally landed this as a hard
// throw, in the same shape as assertNoDuplicateSequences. Running it against
// the CURRENT index surfaced a blast radius the ruling's "at least six"
// framing did not anticipate: 24 files fail the header contract, not 7 --
// and 15 of them (0140-0157, dated 2026-08-12, pre-dating DEC-068's own
// wave-37 introduction) carry NO sha anywhere in their filename or body, so
// "date/branch/sha from the filename" repair is impossible without
// fabricating data. Throwing unconditionally here would make EVERY future
// `npm run verification-log:assemble` / `--check` fail repo-wide over
// legacy debt this task does not own and cannot repair (ONE FILE ONE OWNER
// PER WAVE). Per this task's own DEC-099 abort-condition escape hatch
// ("make the header check --check-only report that does NOT throw, and
// FILE the finding"), this is downgraded to a non-throwing report; see the
// task-w45-f verification-log section for the full before/after evidence
// and the filed wave-46+ finding (owner TBD: needs a design ruling on
// whether pre-DEC-068 sha-less entries are grandfathered or backfilled).
function reportNonConformingHeaders(files: readonly string[]): void {
  const entries = files.map((f) => ({
    file: f,
    firstLine: readFileSync(join(INDEX_DIR, f), "utf8").split("\n")[0] ?? "",
  }));
  const offenders = nonConformingHeaders(entries);
  if (offenders.length > 0) {
    console.error(
      `assemble-verification-log: first line does not match the DEC-068 header contract (\`## <date> <branch> — <scope> @ <sha>\`, EM DASH U+2014, nothing after the sha) in: ${offenders.join(
        ", ",
      )} -- a non-conforming first line is invisible as its own section and silently donates its RESULT:/OPEN ITEMS: lines to the preceding conforming section, overwriting that section's verdict (task-w45-f finding; downgraded to report-only, see docs/verification-log.md task-w45-f section).`,
    );
  }
}

function assemble(): string {
  const files = entryFiles();
  assertNoDuplicateSequences(files);
  reportNonConformingHeaders(files);
  const parts = [PREAMBLE];
  for (const f of files) {
    parts.push(assembleEntry(f, readFileSync(join(INDEX_DIR, f), "utf8")));
  }
  return parts.join("");
}

function nextSeq(): string {
  const files = entryFiles();
  const last = files.length > 0 ? files[files.length - 1] : undefined;
  const lastNum = last ? Number.parseInt(last.slice(0, 4), 10) : 0;
  return String(lastNum + 1).padStart(4, "0");
}

// Guarded so this module can be imported for its pure exports (e.g.
// duplicateSequences) -- by tests -- without triggering a filesystem write
// or process.exit as a side effect of import (matches
// scripts/ensure-dev-vars.ts / scripts/exit-predicate.ts's thin-CLI shape).
if (import.meta.url === `file://${process.argv[1]}`) {
  const mode = process.argv[2];

  if (mode === "--next-seq") {
    process.stdout.write(nextSeq() + "\n");
  } else if (mode === "--renumber") {
    const files = entryFiles();
    const plan = planRenumber(files);
    if (plan.length === 0) {
      console.log("No colliding sequence prefixes -- nothing to renumber.");
    } else {
      const existing = new Set(files);
      for (const { from, to } of plan) {
        if (existing.has(to)) {
          throw new Error(
            `assemble-verification-log --renumber: refusing to rename ${from} -> ${to}, target already exists`,
          );
        }
        existing.delete(from);
        existing.add(to);
      }
      for (const { from, to } of plan) {
        renameSync(join(INDEX_DIR, from), join(INDEX_DIR, to));
        console.log(`Renamed ${from} -> ${to}`);
      }
    }
    writeFileSync(OUTPUT_FILE, assemble());
    console.log(`Wrote ${OUTPUT_FILE} from ${entryFiles().length} entries.`);
  } else if (mode === "--check") {
    const current = readFileSync(OUTPUT_FILE, "utf8");
    const expected = assemble();
    if (current !== expected) {
      console.error(
        "docs/verification-log.md is out of date with docs/verification-log/index/*.md -- run `tsx scripts/assemble-verification-log.ts`",
      );
      process.exit(1);
    }
    console.log("docs/verification-log.md is up to date.");
  } else {
    writeFileSync(OUTPUT_FILE, assemble());
    console.log(`Wrote ${OUTPUT_FILE} from ${entryFiles().length} entries.`);
  }
}
