// Design-decision constants — regenerated by the swarm scribe from
// decisions/DEC-*.md each wave. Code that depends on decision DEC-NNN must
// reference its constant here so the dependency is compile-checked.
// Do not edit by hand below this header.
export const DECISIONS_INDEX = true;

export const DEC_001 = "Single-package repo layout, toolchain, and bindings";
export const DEC_002 = "Pure-core + ports architecture; plain-vitest testability";
export const DEC_003 = "Canonical D1 schema: table names, ID strategy, enum literals";
export const DEC_004 = "Auth: PBKDF2 format, session tokens, cookies, CSRF";
export const DEC_005 = "Route map and admin nav (guessable, two clicks to anything)";
export const DEC_006 = "Mailer port, dev sink, merge-field rendering";
export const DEC_007 = ".ics generation rules (stable UID, SEQUENCE bumps)";
export const DEC_008 = "Form engine: field model, conditional visibility, server-side validation";
export const DEC_009 = "Status pipeline semantics and idempotent acceptance side effects";
export const DEC_010 = "Scheduling model: warn-never-block conflicts, greedy auto-schedule";
export const DEC_011 = "Zero-dependency RFC 4180 CSV utilities";
export const DEC_012 = "Server composition: Hono sub-apps, request context, middleware names, thin handlers";
export const DEC_013 = "API conventions for /api/v1 and the SPA client contract";
export const DEC_014 = "Public CFP account, draft, and claim-token flow (no inbox required)";
export const DEC_015 = "Additive migration discipline; submission_track join; form.tracks_json";
export const DEC_016 = "Submissions list API contract; locked built-in fields persist to real columns";
export const DEC_017 = "Wave-3 schema additions in one migration; legacy track columns frozen";
export const DEC_018 = "Review API contract, criteria kinds, reviewer UX, and /api/v1/me";
export const DEC_019 = "Deliberate-notify compose pipeline: recipients, atomic preview, 100-cap, feedback attach";
export const DEC_020 = "File pipeline: upload validation, version chains, authenticated serving, comments, approval";
export const DEC_021 = "Agenda API and drag-drop UI contract; slot writes bump ics_sequence";
export const DEC_022 = "Public surfaces: single query gate, SSR + embeds, itinerary .ics, stage-1 cache headers";
export const DEC_023 = "Onboarding grid API, task CRUD, and due-date reminder cron";
export const DEC_024 = "SPA shared modules for wave 3: useCurrentEvent, useMe, api.ts as sole wire";
