// Design-decision constants — regenerated by the swarm scribe from
// decisions/DEC-*.md each wave. Code that depends on decision DEC-NNN must
// reference its constant here so the dependency is compile-checked.
// Do not edit by hand below this header.
export const DECISIONS_INDEX = true;
